Iter22
ETretyakov/metrix pull request #21
Opened 2024-09-15 15:20 UTC by ETretyakov

2024-09-20 21:31 UTC, avhitrov requested changes
Несколько замечаний в комментариях к коду.

2024-09-20 21:31 UTC, avhitrov commented on internal/config/config.go
> +	}
В соответствии с ТЗ файловый конфиг должен иметь самый низкий приоритет. В данной реализации значения из файлового конфига перетирают значения, установленные с помощью переменных окружения и аргументов командной строки.

2024-09-20 21:31 UTC, avhitrov commented on internal/handlers/metrics.go
> +	fmt.Println(">>>> handler", metricsIn)
Это такая странная отладка? Вроде уже логгер имплементирован.

2024-09-20 21:31 UTC, avhitrov commented on internal/middlewares/decryption.go
> +					context.TODO(),
А отчего не r.Context()? Касается всех случаев применения в мидлварях.

2024-09-20 21:31 UTC, avhitrov commented on pkg/agent/config/config.go
> +	}
Аналогично серверу

2024-09-26 06:30 UTC, ETretyakov commented on internal/config/config.go
> +	}
Поменял порядок

2024-09-26 06:30 UTC, ETretyakov commented on internal/handlers/metrics.go
> +	fmt.Println(">>>> handler", metricsIn)
убрал принты

2024-09-26 06:30 UTC, ETretyakov commented on internal/middlewares/decryption.go
> +					context.TODO(),
заменил во все проекте

2024-09-26 06:30 UTC, ETretyakov commented on pkg/agent/config/config.go
> +	}
Поменял порядок

2024-10-23 21:11 UTC, avhitrov approved these changes
Все замечания устранены, отлично!

2024-10-24 05:46 UTC, merged