Iter25
ETretyakov/metrix pull request #23
Opened 2024-10-23 09:35 UTC by ETretyakov

2024-10-23 21:25 UTC, avhitrov requested changes
- Замечание в коде относительно алгоритма использования проверки по подсети
- Для gRPC-сервера необходимо создать интерсептор, аналогичный SubnetMiddleware, который также должен активироваться только при наличии данных о подсети в конфигурации запуска.

2024-10-23 21:25 UTC, avhitrov commented on internal/http/routes.go
> +	m.Use(middlewares.SubnetMiddleware)
Функционал должен включаться только в случае, если Subnet определена.

2024-10-24 05:59 UTC, ETretyakov commented on internal/http/routes.go
> +	m.Use(middlewares.SubnetMiddleware)
поправил в самой middleware

2024-10-28 20:28 UTC, avhitrov approved these changes
Все отлично!

2024-10-29 06:13 UTC, merged