Iter5
ETretyakov/metrix pull request #5
Opened 2024-05-05 19:16 UTC by ETretyakov

2024-05-08 19:59 UTC, avhitrov requested changes
1. Гонки на сервере при запросе списка всех метрик
2. Несоответствие ТЗ в области приоритетов расчета параметров конфигурации.
3. Закомментированные куски кода в исходных текстах.

2024-05-08 19:59 UTC, avhitrov commented on internal/database/memory_storage.go
> +func (s *MemoryStorage) Keys(namespace string) ([]string, error) {
В этой функции ловим гонки. Уровень второй иллюзии (https://t.me/bushigo/24).

```
==================
WARNING: DATA RACE
Write at 0x00c00001cbd0 by goroutine 8094:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  metrix/internal/database.(*MemoryStorage).Set()
      C:/work/src/github.com/ETretyakov/metrix/internal/database/memory_storage.go:39 +0x12c
  metrix/internal/infrastructure.(*StorageHandler).Set()
      C:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/storage_handler.go:28 +0x67
  metrix/internal/interfaces.(*WidgetRepository).Update()
      C:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_repository.go:40 +0x1f7
  metrix/internal/usecases.(*WidgetInteractor).Update()
      C:/work/src/github.com/ETretyakov/metrix/internal/usecases/widget_interactor.go:31 +0x952
  metrix/internal/interfaces.(*WidgetController).Update()
      C:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_controller.go:106 +0x98c
  metrix/internal/interfaces.(*WidgetController).Update-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/gorilla/mux.(*Router).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x371
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous read at 0x00c00001cbd0 by goroutine 8093:
  runtime.mapiterinit()
      C:/Apps/Go/src/runtime/map.go:816 +0x0
  metrix/internal/database.(*MemoryStorage).Keys()
      C:/work/src/github.com/ETretyakov/metrix/internal/database/memory_storage.go:47 +0xa4
  metrix/internal/infrastructure.(*StorageHandler).Keys()
      C:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/storage_handler.go:37 +0x3f
  metrix/internal/interfaces.(*WidgetRepository).Keys()
      C:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_repository.go:89 +0x61
  metrix/internal/usecases.(*WidgetInteractor).Keys()
      C:/work/src/github.com/ETretyakov/metrix/internal/usecases/widget_interactor.go:60 +0x388
  metrix/internal/interfaces.(*WidgetController).Keys()
      C:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_controller.go:131 +0x35a
  metrix/internal/interfaces.(*WidgetController).Keys-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/gorilla/mux.(*Router).ServeHTTP()
      C:/Users/ahitr/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x371
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 8094 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x604
  metrix/internal/infrastructure.Dispatch()
      C:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/router.go:36 +0x1a
  main.main()
      C:/work/src/github.com/ETretyakov/metrix/cmd/server/main.go:29 +0x332

Goroutine 8093 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x604
  metrix/internal/infrastructure.Dispatch()
      C:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/router.go:36 +0x1a
  main.main()
      C:/work/src/github.com/ETretyakov/metrix/cmd/server/main.go:29 +0x332
==================
```

2024-05-08 19:59 UTC, avhitrov commented on internal/interfaces/widget_controller.go
> +	// }
Не следует в исходниках оставлять закомментированные куски кода. Это противоречит концепции системы хранения версий.

2024-05-08 19:59 UTC, avhitrov commented on pkg/agent/config/config.go
> +	}
По ТЗ переменные окружения должны иметь приоритет перед аргументами командной строки. В данной реализации сделано наоборот.

2024-05-14 23:17 UTC, avhitrov requested changes
Два из трех замечаний исправлены: закомментированный код удален, приоритет заполнения конфига сделан, как требует ТЗ.

Гонки остались. Код, который решает проблему, почему-то закомментирован.

2024-05-14 23:17 UTC, avhitrov commented on internal/database/memory_storage.go
> +
А почему код закомментирован? Гонки от этого никуда не делись.
```
==================
WARNING: DATA RACE
Write at 0x00c00008aba0 by goroutine 5958:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  metrix/internal/database.(*MemoryStorage).Set()
      D:/work/src/github.com/ETretyakov/metrix/internal/database/memory_storage.go:39 +0x12c
  metrix/internal/infrastructure.(*StorageHandler).Set()
      D:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/storage_handler.go:28 +0x67
  metrix/internal/interfaces.(*WidgetRepository).Update()
      D:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_repository.go:40 +0x1f7
  metrix/internal/usecases.(*WidgetInteractor).Update()
      D:/work/src/github.com/ETretyakov/metrix/internal/usecases/widget_interactor.go:31 +0x952
  metrix/internal/interfaces.(*WidgetController).Update()
      D:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_controller.go:98 +0x98c
  metrix/internal/interfaces.(*WidgetController).Update-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/gorilla/mux.(*Router).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x371
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous read at 0x00c00008aba0 by goroutine 5957:
  runtime.mapiterinit()
      C:/Apps/Go/src/runtime/map.go:816 +0x0
  metrix/internal/database.(*MemoryStorage).Keys()
      D:/work/src/github.com/ETretyakov/metrix/internal/database/memory_storage.go:50 +0xa4
  metrix/internal/infrastructure.(*StorageHandler).Keys()
      D:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/storage_handler.go:37 +0x3f
  metrix/internal/interfaces.(*WidgetRepository).Keys()
      D:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_repository.go:89 +0x61
  metrix/internal/usecases.(*WidgetInteractor).Keys()
      D:/work/src/github.com/ETretyakov/metrix/internal/usecases/widget_interactor.go:60 +0x388
  metrix/internal/interfaces.(*WidgetController).Keys()
      D:/work/src/github.com/ETretyakov/metrix/internal/interfaces/widget_controller.go:116 +0x35a
  metrix/internal/interfaces.(*WidgetController).Keys-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/gorilla/mux.(*Router).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x371
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 5958 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x604
  metrix/internal/infrastructure.Dispatch()
      D:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/router.go:36 +0x1a
  main.main()
      D:/work/src/github.com/ETretyakov/metrix/cmd/server/main.go:29 +0x332

Goroutine 5957 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x604
  metrix/internal/infrastructure.Dispatch()
      D:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/router.go:36 +0x1a
  main.main()
      D:/work/src/github.com/ETretyakov/metrix/cmd/server/main.go:29 +0x332
==================
```

2024-05-15 07:56 UTC, ETretyakov commented on internal/database/memory_storage.go
> +
меня заглючило ночью видимо, я тестировал эту часть на гонки - коментил и раскоментил и забыл в итоге раскоментить

2024-05-18 22:22 UTC, avhitrov approved these changes
Все ок.

2024-06-22 08:55 UTC, merged