Iter9
ETretyakov/metrix pull request #9
Opened 2024-05-26 20:17 UTC by ETretyakov

2024-06-09 23:19 UTC, avhitrov requested changes
1. Не вполне верная работа с конфигами, подробности в комментариях
2. Почему-то при указании при запуске `.\server.exe -a :8080 -f=""` в момент завершения программы вылетает
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x14043c5c5]

goroutine 1 [running]:
metrix/internal/infrastructure.Dispatch({0x140617db8, 0xc000072080}, {0xc00009e0db, 0x5}, {0x140617bf8, 0xc000062008})
        C:/work/src/github.com/ETretyakov/metrix/internal/infrastructure/router.go:77 +0xf65
main.main()
        C:/work/src/github.com/ETretyakov/metrix/cmd/server/main.go:42 +0x47b
```
3. Неверное выставление статусов в http-хендлерах.

2024-06-09 23:19 UTC, avhitrov commented on internal/config/config.go
> +	}
```suggestion
	_, exists := os.Getenv("STORE_INTERVAL")
	if !exists {
		config.StoreInterval = storeInterval
	}
```
STORE_INTERVAL может быть равен нулю, в этом случае все равно необходимо соблюсти приоритет переменных окружения перед флагами.

2024-06-09 23:19 UTC, avhitrov commented on internal/config/config.go
> +	envRestore := os.Getenv("RESTORE")
Аналогично RESTORE=false должна иметь приоритет перед -r=true

2024-06-09 23:19 UTC, avhitrov commented on internal/infrastructure/storage_handler.go
Все функции данного объекта занимаются мартышкиным трудом по перекладыванию ответов от стораджа. Ergo - прослойка ненужная.

2024-06-09 23:19 UTC, avhitrov commented on internal/interfaces/widget_controller.go
> +		w.WriteHeader(http.StatusInternalServerError)
Если после выставления статуса не выйти из функции по `return`, то будет выставлен еще один статус `w.WriteHeader(http.StatusOK)`, что приведет к возникновению в логах ошибки
```
ge:StackSys:131072 default:gauge:Sys:6.836224e+06 default:gauge:TotalAlloc:3.0302216e+07]2024/06/10 01:58:48 http: superfluous response.WriteHeader call from metrix/internal/logger.(*loggingResponseWriter).WriteHeader (logger.go:70)
```

2024-06-09 23:19 UTC, avhitrov commented on internal/interfaces/widget_controller.go
> +	err = json.NewEncoder(w).Encode(schemeOut)
Данный вывод тела ответа автоматически дергает под капотом выставление статуса (200 OK). Поэтому следующая за ним попытка выставить статус `w.WriteHeader(http.StatusOK)` рождает ошибку
```
http: superfluous response.WriteHeader call from metrix/internal/logger.(*loggingResponseWriter).WriteHeader (logger.go:70)
```

2024-06-09 23:19 UTC, avhitrov commented on internal/usecases/widget_interactor.go
Похоже на еще одну компоненту-прокси.

2024-06-09 23:19 UTC, avhitrov commented on pkg/agent/watcher/watcher.go
> +			w.PollCount = 0
```suggestion
			if err == nil {
				w.PollCount = 0
			}
```

2024-06-10 20:05 UTC, ETretyakov commented on internal/config/config.go
> +	}
Переписано через рефлексию

2024-06-10 20:05 UTC, ETretyakov commented on internal/config/config.go
> +	envRestore := os.Getenv("RESTORE")
Переписано через рефлексию

2024-06-10 20:06 UTC, ETretyakov commented on internal/infrastructure/storage_handler.go
убрал прослойку

2024-06-10 20:06 UTC, ETretyakov commented on internal/interfaces/widget_controller.go
> +		w.WriteHeader(http.StatusInternalServerError)
переписано

2024-06-10 20:06 UTC, ETretyakov commented on internal/interfaces/widget_controller.go
> +	err = json.NewEncoder(w).Encode(schemeOut)
переписано

2024-06-10 20:06 UTC, ETretyakov commented on internal/usecases/widget_interactor.go
убрано

2024-06-10 20:06 UTC, ETretyakov commented on pkg/agent/watcher/watcher.go
> +			w.PollCount = 0
это хорошо подмечено, спасибо

2024-06-13 22:21 UTC, avhitrov approved these changes
Довольно много ошибок работы с БД, организации транзакций и т.д. Поскольку данная тема входит в сдаваемый спринт, ставлю аппрув, но при этом все изменения, касающиеся имплементируемых итераций с 10 и дальше желаю видеть в следующем ПР. И не надо, пожалуйста, запутывать ревью.

2024-06-13 22:21 UTC, avhitrov commented on internal/repository/metrics.go
> +	}
Здесь необходимо добавить проверку на результат последней операции чтения выдернутого из БД списка:
```
err = rows.Err()
if err != nil {
    return nil, err
}
```
https://go.dev/doc/database/querying

2024-06-13 22:21 UTC, avhitrov commented on internal/repository/metrics.go
> +	}
Эта ошибка имеет смысл только для QueryRow().Scan() - то есть при вызове функции, работающей с одной записью. И рождается эта ошибка в результате Scan. В случае с выбором нескольких строк никакая ошибка sql.ErrNoRows взведена не будет.

2024-06-13 22:21 UTC, avhitrov commented on internal/repository/metrics.go
> +	defer tx.Commit()
```suggestion
	defer tx.Rollback()
```
`tx.Commit()` дергается только в случае отсутствия ошибки в конце работы с вызовами БД

Но в данном случае вообще нет смысла открывать транзакцию, так как в ее рамках будет выполняться всего один запрос, он и так выполнится транзакционно-безопасно.

2024-06-13 22:21 UTC, avhitrov commented on internal/repository/metrics.go
> +	defer tx.Commit()
```suggestion
	defer tx.Rollback()
```

2024-06-13 22:21 UTC, avhitrov commented on internal/repository/metrics.go
> +	}
```
tx.Commit()
```

2024-06-13 22:21 UTC, avhitrov commented on migrations/20240606104932_init_metrix.sql
> +	CONSTRAINT mtr_metrics_pk PRIMARY KEY (id)
```suggestion
	CONSTRAINT mtr_metrics_pk PRIMARY KEY (id, mtype)
```
ТЗ не запрещает создавать две записи с одним названием и разными типами.

2024-06-22 08:56 UTC, merged